#!/bin/bash
EXERCISM_DIR=$HOME/Playground/exercism

echo "Type exercise and track (ex: elixir captains-log):"
read TRACK EXERCISE

WORKSPACE_DIR="$EXERCISM_DIR/$TRACK/$EXERCISE"

if [ ! -d $WORKSPACE_DIR ]; then
  echo "Downloading $EXERCISE for $TRACK..."
  exercism download --exercise $EXERCISE --track $TRACK
else
  echo "$TRACK/$EXERCISE is exists"
fi

tmux send "cd $WORKSPACE_DIR" C-m
tmux send "hx ." C-m
tmux split-window -v
tmux send "cd $WORKSPACE_DIR" C-m
tmux send C-l
tmux resize-pane -D 10
tmux select-pane -U
