{
  config,
  pkgs,
  modulesPath,
  userConfig,
  ...
}: {
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    /etc/nixos/orbstack.nix
    # Include the container-specific autogenerated configuration.
    /etc/nixos/incus.nix
    ../../modules/system/emacs
  ];

  nix = {
    settings = {
      experimental-features = ["nix-command" "flakes"];
      auto-optimise-store = true;
      trusted-users = ["root" "nyeong"];
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };

  users.users.${userConfig.username} = {
    uid = 501;
    extraGroups = ["wheel" "orbstack"];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/nyeong";
    homeMode = "700";
    useDefaultShell = true;
    shell = pkgs.zsh;
  };

  programs.zsh.enable = true;

  environment.systemPackages = with pkgs; [
    vim
    git
    htop
    bottom
    helix
    wget
    nodejs
  ];

  security.sudo.wheelNeedsPassword = false;
  users.mutableUsers = false;
  time.timeZone = "Asia/Seoul";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  system.stateVersion = "25.05";
}
