#!/bin/bash

TS_SETUP_DIR="$HOME/.dotfiles/tmux/setup"

show_setups() {
  setups=( $(ls $TS_SETUP_DIR) )
  echo ${setups[@]}
}

usage() {
  cat <<EOF
Usage: $(basename $0) setup-name [-t window|session|current]
--- setups -----------------------------
EOF
  show_setups
}

if [[ -z $1 ]]; then
  usage
  exit 0
fi

SETUP_PATH="$TS_SETUP_DIR/$1"
shift
if [[ ! -f $SETUP_PATH ]]; then
  usage
  exit 0
fi

TYPE="window"
while getopts "ht:" opt; do
  case "${opt}" in
    t)
      if [[ ! $OPTARG =~ ^(window|session|current)$ ]]; then
        usage
        exit 0
      fi
      TYPE=$OPTARG
      ;;
    h | *)
      usage
      exit 0
      ;;
  esac
done

CURRENT_SESSION=$(tmux display-message -p '#S')

case $TYPE in
  current)
    sh -c $SETUP_PATH
    ;;
  window)
    tmux new-window -n $1
    tmux send-keys -t "$CURRENT_SESSION:$1" "sh -c $SETUP_PATH" C-m
    ;;
  session)
    tmux new-session $SETUP_PATH
    ;;
esac
