#! /bin/zsh
[[ -z $TMUX ]] && exec tmux new-session -A -s workspace

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Use zinit
if [[ -d ~/.zinit ]]; then
  source ~/.zinit/bin/zinit.zsh
  autoload -Uz _zinit
  (( ${+_comps} )) && _comps[zinit]=_zinit

  zinit ice depth=1; zinit light romkatv/powerlevel10k

  ZSH_EXPAND_ALL_DISABLE=word

  # 여기에 플러그인을 추가
  zinit light simnalamburt/zsh-expand-all
  zinit light zdharma/fast-syntax-highlighting
  zinit light zsh-users/zsh-completions
  zinit light zsh-users/zsh-autosuggestions
  zinit light zsh-users/zsh-history-substring-search
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down

  autoload -Uz compinit
  compinit

  zinit cdreplay
  
  # zsh-users/zsh-completions
  fpath=(/usr/local/share/zsh-completions $fpath)
  fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
  
fi

zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu select
export TIME_STYLE='long-iso'

# GPG setup
export GPG_TTY=$(tty)

# enable c-x to edit command line
autoload -z edit-command-line
zle -N edit-command-line
bindkey '^X' edit-command-line

# source zsh configs
for file in ~/.dotfiles/zsh/*.zsh; do . $file; done

[[ -d ~/.local/bin ]] && export PATH=$PATH:~/.local/bin/

source /Users/nyeong/.config/broot/launcher/bash/br
source ~/.asdf/plugins/java/set-java-home.zsh
source ~/.zprofile

[ -f "/Users/nyeong/.ghcup/env" ] && source "/Users/nyeong/.ghcup/env" # ghcup-env