#! /bin/zsh
[[ -z "$TMUX" ]] && exec tmux new-session -A -s workspace

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Use zinit
if [[ -d ~/.zinit ]]; then
  source ~/.zinit/bin/zinit.zsh
  autoload -Uz _zinit
  (( ${+_comps} )) && _comps[zinit]=_zinit

  zinit ice depth=1; zinit light romkatv/powerlevel10k

  ZSH_EXPAND_ALL_DISABLE=word

  # 여기에 플러그인을 추가
  zinit light simnalamburt/zsh-expand-all
  zinit light zdharma/fast-syntax-highlighting
  zinit light zsh-users/zsh-completions
  zinit light zsh-users/zsh-autosuggestions
  zinit light zsh-users/zsh-history-substring-search
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down

  autoload -Uz compinit
  compinit

  zinit cdreplay
fi

zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu select
export TIME_STYLE='long-iso'

# source zsh configs
for file in ~/.config/zsh/*.zsh; do . $file; done

# zoxide
[[ $+command[zoxide] ]] && eval "$(zoxide init zsh)"

# cargo
[[ -d ~/.cargo ]] && export PATH=$PATH:~/.cargo/bin/

# asdf-vm
[[ -d ~/.asdf ]] && . ~/.asdf/asdf.sh

# zsh
[[ -f ~/.zshrc.local ]] && . ~/.zshrc.local
